temporal_scope:
  start: "2017-01-01"
  end: "2017-01-03"
  frequency: "1h"
# provide a list of sources and set their priority order. Options include: entsoe, neso, opsd
load_sources:
  - entsoe
  - neso
  - opsd

gap_filling:
  mode: advanced

  basic:
    rules:
      - name: interpolate_short_gaps
        method: linear_interpolation
        max_gap: 3h

      - name: average_adjacent_weeks
        method: average_periods
        max_gap: 326h
        source_offsets:
          - -7d
          - 7d

      - name: copy_previous_week
        method: copy_periods
        max_gap: 168h
        source_offset: -168h
        require_complete_source: true

      - name: copy_following_week
        method: copy_periods
        max_gap: 168h
        source_offset: 168h
        require_complete_source: true

  advanced:
    auxiliary_data:
      basic_cleaning:
        enabled: true

    sources:
      alb_from_gbr_alb_winter:
        method: construct_from_sources
        periods:
          - country: GBR
            start: "2024-01-01"
            end: "2024-02-01"
            weight: 1
        scaling:
          method: match_energy
          periods:
            - country: ALB
              start: "2024-01-01"
              end: "2024-02-01"
              weight: 1

      alb_from_alb_2024:
        method: construct_from_sources
        periods:
          - country: ALB
            start: "2024-01-01"
            end: "2024-01-03"
            weight: 1
        scaling:
          method: match_energy
          periods:
            - country: ALB
              start: "2024-01-01"
              end: "2024-01-03"
              weight: 1

      mne_from_srb:
        method: construct_from_sources
        periods:
          - country: SRB
            start: "2022-03-01"
            end: "2022-04-01"
            weight: 1

      alb_external_test:
        method: external_profile
        file: alb_external_test.csv

    rules:
      - name: build_alb_from_gbr_alb_winter
        country: ALB
        start: "2022-01-01"
        end: "2022-02-01"
        scope: fill_gaps
        source: alb_from_gbr_alb_winter

      - name: build_alb_from_alb_2024
        country: ALB
        start: "2017-01-01"
        end: "2017-01-03"
        scope: overwrite
        source: alb_from_alb_2024

      - name: example_inactive_mne_override
        country: MNE
        start: "2020-03-01"
        end: "2020-04-01"
        scope: fill_gaps
        source: mne_from_srb

      - name: test_external_profile_overwrite
        country: ALB
        start: "2022-01-01 00:00"
        end: "2022-01-08 00:00"
        scope: overwrite
        source: alb_external_test
